### ISSUE TITLE
Issue 1: Add feature - average number of project participated per year

### ISSUE THREAD

**Issue by baiyuchen02** [dsi-principles-prog/midterm-baiyuchen02#1]
Create a function that will add a new column of average number of project participated per year. Average number of project participated per year (avg_num_proj_per_year) = number of project participated (number_project) / year spend in the company (time_spend_company).

New feature: avg_num_proj_per_year
Column used: number_project, time_spend_company

The expected outcome of the new column after calling the function should be like the picture below.
<img width="234" alt="Screen Shot 2019-10-29 at 04 46 31" src="https://user-images.githubusercontent.com/33174262/67757366-ac11ad00-fa09-11e9-8062-cef56e6897fa.png">

You may test whether avg_num_proj_per_year is between 0 and 7 (maximum of number_project) inclusively.
Assert function may used: within_bounds()

Brief instruction: Fill in "## New feature 3" and "## Test new feature 3"

**Comment by drewflaherty95** [comment]
added avg_num_proj_per_year feature, closes #1
